# Generated by Django 2.0.1 on 2018-10-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20181018_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to='course/video/%Y/%m', verbose_name='视频文件'),
        ),
    ]
