# Generated by Django 2.0.1 on 2018-10-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20181023_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nike_name',
            new_name='nick_name',
        ),
    ]
